on:
  push:
    branches: [rev10]
  schedule:
    - cron: "0 21 * * *"

jobs:
  test_linux:
    runs-on: ubuntu-latest
    steps:
      - name: Download source
        uses: actions/checkout@v3
      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
      - name: Build ffi-test
        run: gcc -shared -o tests/res/ffi-test.so tests/res/ffi-test.c
      - name: Install dependencies
        run: shards install --without-development
      - name: Build CLI, NKAS, NKI
        run: shards build --without-development
      - name: Run language tests
        run: bin/novika -:abort-on-permission-request ffi disk tests/res/ffi-test.so tests
      - name: Build tests via NKAS
        run: bin/nkas -cb:b ffi disk tests/res/ffi-test.so tests tests/tests.nki
      - name: Copy ffi-test shared object to tests directory
        run: cp tests/res/ffi-test.so tests/ffi-test.so
      - name: Run the tests image using NKI
        run: bin/nki tests/tests.nki
      - name: Run resolver tests
        run: |
          cd tests/_resolver
          bash run.sh
  test_windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Download source
        uses: actions/checkout@v3
      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
      - name: Build ffi-test
        run: gcc -shared -o tests/res/ffi-test.dll tests/res/ffi-test.c
      - name: Install dependencies
        run: shards install --without-development
      - name: Build CLI, NKAS, NKI
        run: shards build --without-development
      - name: Run language tests
        run: bin/novika -:abort-on-permission-request ffi disk tests/res/ffi-test.dll tests
      - name: Build tests via NKAS
        run: bin/nkas -cb:b ffi disk tests/res/ffi-test.dll tests tests/tests.nki
      - name: Copy ffi-test shared object to tests directory
        run: cp tests/res/ffi-test.dll tests/ffi-test.dll
      - name: Run the tests image using NKI
        run: bin/nki tests/tests.nki
